name: expense_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.0.3
  
  # Utilities
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  
  # Charts
  fl_chart: ^1.1.1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # NEW SECTION: Add the assets folder declaration here
  assets: 
    - assets/